### PR TITLE
Django 1.8 compability

### PR DESCRIPTION
**Pull request by Cybran111**
Added forgotten migration
Added requirements.txt
Removed deprecated decorator
Removed unused import from setup.py

Migrations drove me nuts when I was trying to run the example first.

### CODE REVIEW

**Comment by Cybran111** [comment]
It seems to me I should dive deeply in what goes on in this function.
transaction.rollback() is also forbidden when "atomic" is active

**Comment by gcaprio** [comment]
hey @Cybran111 Yeah, I noticed that too & tried the quick suggestion. There's something deeper going on. Thanks for the PR though, will happily merge it w/o the atomic change.

**Comment by Cybran111** [comment]
@gcaprio there is no need in atomic transaction and I should revert the 2nd commit? I understood correctly?

**Comment by gcaprio** [comment]
@Cybran111 Yes, that'd correct.

**Pull request closed without merging**
