### PR TITLE
Complete setup of project

### PR DESCRIPTION
**Pull request by gabivoicu**
add a couple more steps needed for successfully setting up app
tweak formatting

### CODE REVIEW

**Comment by gabivoicu** [comment]
@gcaprio Not sure where `ls` folder came from, should I maybe add it to `.gitignore` and re-commit?

**Comment by gabivoicu** [comment]
Nevermind, I realized what I had done and where that folder came from. removed!

**Comment by gcaprio** [comment]
Awesome, thanks!

**Comment by gabivoicu** [comment]
@gcaprio What about the security thing?

**Comment by gcaprio** [comment]
@gabivoicu oh sorry totally missed that. So that was added by Django 1.7 by default? it's not in my local project. So yeah, for now maybe add something about removing it.

**Pull request merged**
